services:
  portainer:
    image: portainer/portainer-ce:2.33.7
    container_name: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer_data:/data
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.portainer.rule=Host(`portainer.jamesmassucco.com`)'
      - 'traefik.http.routers.portainer.entrypoints=websecure'
      - 'traefik.http.routers.portainer.tls=true'
      - 'traefik.http.routers.portainer.tls.certresolver=cloudflare'
      - 'traefik.http.routers.portainer.middlewares=oauth-auth,ratelimit'
      - 'traefik.http.services.portainer.loadbalancer.server.port=9000'
    healthcheck:
      test: ['CMD', 'wget', '-qO-', 'http://127.0.0.1:9000/api/system/status']
      interval: 5s
      timeout: 1s
      retries: 3
      start_period: 10s
    networks:
      - web
    restart: unless-stopped

volumes:
  portainer_data:

networks:
  web:
    external: true
